add rbac module
go-chassis/sc-client pull request #38
Opened 2020-12-18 07:06 UTC by hityc2019

add rbac module client

2020-12-26 00:49 UTC, tianxiaoliang commented
请先解决门禁错误

2020-12-28 06:52 UTC, hityc2019 commented
客户端使用的service-center镜像是四个月前上传的，需要更新镜像，用最新commit或者1.3版本本地都能通过，而Ubuntu环境下使用latest镜像无法测试通过，GetAllApplications和GetAllResources会报错

2020-12-28 07:40 UTC, tianxiaoliang requested changes

2020-12-28 07:40 UTC, tianxiaoliang commented on rbacframe/account.go
> +package rbacframe
rbac model 挪到go-chassis/cari的rbac下边

2020-12-28 07:40 UTC, tianxiaoliang commented on client.go
> +	header.Set(HeaderAuth, "Bearer "+token)
必须通过SignRequest完成，而不是每次请求都塞header

2021-01-05 07:54 UTC, tianxiaoliang commented
解决下门禁问题

2021-01-05 08:07 UTC, hityc2019 commented
> 解决下门禁问题

需要替换一下service-center镜像，貌似客户端使用的service-center镜像版本导致的

2022-07-20 08:51 UTC, closed without merging